--- !ditz.rubyforge.org,2008-03-06/project 
name: cadabra
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: cadabra
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.144"
  status: :released
  release_time: 2008-08-29 11:39:41.850751 Z
  log_events: 
  - - 2008-08-29 11:38:36.334943 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - created
    - This release has preliminary undo/redo support in the GUI.
  - - 2008-08-29 11:39:41.850775 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.0"
  status: :released
  release_time: 2008-12-11 16:25:57.475408 Z
  log_events: 
  - - 2008-08-29 11:41:30.088931 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - created
    - |-
      The first version with a more or less feature-complete GUI (full
      documentation and undo/redo).
  - - 2008-12-11 16:25:57.475432 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - released
    - First officially stable release.
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.05"
  status: :released
  release_time: 2009-06-03 21:12:40.313354 Z
  log_events: 
  - - 2009-01-21 22:42:59.204261 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - created
    - Fixes bugs related to handling of fractions and partial integration.
  - - 2009-06-03 21:12:40.313385 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.12"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-06-03 21:11:35.181237 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - created
    - ""
