--- !ditz.rubyforge.org,2008-03-06/project 
name: cadabra
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: cadabra
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.144"
  status: :released
  release_time: 2008-08-29 11:39:41.850751 Z
  log_events: 
  - - 2008-08-29 11:38:36.334943 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - created
    - This release has preliminary undo/redo support in the GUI.
  - - 2008-08-29 11:39:41.850775 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.0"
  status: :released
  release_time: 2008-12-11 16:25:57.475408 Z
  log_events: 
  - - 2008-08-29 11:41:30.088931 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - created
    - |-
      The first version with a more or less feature-complete GUI (full
      documentation and undo/redo).
  - - 2008-12-11 16:25:57.475432 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - released
    - First officially stable release.
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.05"
  status: :released
  release_time: 2009-06-03 21:12:40.313354 Z
  log_events: 
  - - 2009-01-21 22:42:59.204261 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - created
    - Fixes bugs related to handling of fractions and partial integration.
  - - 2009-06-03 21:12:40.313385 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.12"
  status: :released
  release_time: 2009-08-18 17:37:31.895514 Z
  log_events: 
  - - 2009-06-03 21:11:35.181237 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - created
    - ""
  - - 2009-08-18 17:37:31.895540 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - released
    - Long ago...
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.15"
  status: :released
  release_time: 2009-08-18 17:37:56.437346 Z
  log_events: 
  - - 2009-08-18 17:37:15.979707 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - created
    - Stable version release before Ubuntu Karmic 9.10 freeze.
  - - 2009-08-18 17:37:56.437371 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.17"
  status: :released
  release_time: 2010-01-28 13:43:06.931548 Z
  log_events: 
  - - 2009-09-02 19:07:21.289887 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - created
    - ""
  - - 2010-01-28 13:43:06.931573 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - released
    - Released on PPA and as source only.
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.18"
  status: :released
  release_time: 2010-02-06 18:10:31.298472 Z
  log_events: 
  - - 2010-01-28 13:41:27.478216 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - created
    - to be uploaded to Debian in time for Ubuntu Lucid freeze
  - - 2010-02-06 18:10:31.298499 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "1.21"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-02-07 21:17:02.868424 Z
    - Kasper Peeters <kasper.peeters@aei.mpg.de>
    - created
    - ""
